[package]
name = "encodedlux/bufnet"
description = "Modern declarative buffer networking."
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["README.md", "src", "src/**", "default.project.json", "wally.toml"]

[dependencies]
