[package]
name = "encodedlux/bufnet"
description = "Lightweight networking library for Roblox built for performance, type safety and efficient data communication."
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["README.md", "src", "src/**", "default.project.json", "wally.toml"]

[dependencies]
